from openai import OpenAI, APIError
from config import MODEL_PATHS, DEEPSEEK_API_KEY, CHATGPT_API_KEY
# from transformers import AutoTokenizer, AutoModelForCausalLM
# from transformers import BitsAndBytesConfig
# import torch


def get_deepseek_response(prompt, model="deepseek-chat", generation_config=None):
    """
    Sends a prompt to the DeepSeek API and retrieves the generated response.

    Args:
        prompt (str): The user's input prompt to be sent to the language model.
        model (str): The model to use for generating the response. Defaults is "deepseek-chat".
        generation_config (dict, optional): Configuration for generation parameters such as
            "max_tokens", "temperature", and "top_p". If None, a default config is used.

    Returns:
        - model (str): The name of the model used.
        - generated_content (str): The content generated by the model.
        - input_tokens (int): The number of tokens in the input prompt.
        - output_tokens (int): The number of tokens in the generated output.

    Raises:
        APIError: If there is an error returned from the API.
        Exception: For any unexpected errors.
    """
    client = OpenAI(api_key=DEEPSEEK_API_KEY, base_url="https://api.deepseek.com")

    if generation_config is None:
        generation_config = {
            "max_tokens": 2048,
            "temperature": 1.3,
            "top_p": 0.9,
        }

    try:
        response = client.chat.completions.create(
            model=model,
            **generation_config,
            messages=[
                {"role": "system", "content": "You are a helpful assistant"},
                {"role": "user", "content": prompt},
            ],
            stream=False
        )

        model = response.model
        generated_content = response.choices[0].message.content
        input_tokens = response.usage.prompt_tokens
        output_tokens = response.usage.completion_tokens

        return model, generated_content, input_tokens, output_tokens

    except APIError as e:
        print(f"API Error: {e}")
        return None
    except Exception as e:
        print(f"Unexpected Error: {e}")
        return None


def get_chatgpt_response(prompt, model="gpt-4o-mini-2024-07-18", generation_config=None):
    """
    Sends a prompt to the ChatGPT API and retrieves the generated response.

    Args:
        prompt (str): The user's input prompt to be sent to the language model.
        model (str): The model to use for generating the response. Default is "gpt-4o-mini-2024-07-18".
        generation_config (dict, optional): Configuration for generation parameters such as
            "max_tokens", "temperature", and "top_p". If None, a default config is used.

    Returns:
        - model (str): The name of the model used.
        - generated_content (str): The content generated by the model.
        - input_tokens (int): The number of tokens in the input prompt.
        - output_tokens (int): The number of tokens in the generated output.

    Raises:
        APIError: If there is an error returned from the API.
        Exception: For any unexpected errors.
    """
    client = OpenAI(api_key=CHATGPT_API_KEY)

    if generation_config is None:
        generation_config = {
            "max_tokens": 2048,
            "temperature": 1.0,
            "top_p": 0.9,
        }

    try:
        response = client.chat.completions.create(
            model=model,
            **generation_config,
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt}
            ],
            stream=False
        )

        model = response.model
        generated_content = response.choices[0].message.content
        input_tokens = response.usage.prompt_tokens
        output_tokens = response.usage.completion_tokens

        return model, generated_content, input_tokens, output_tokens

    except APIError as e:
        print(f"API Error: {e}")
        return None
    except Exception as e:
        print(f"Unexpected Error: {e}")
        return None


# def get_local_response(prompt, model):
#     """
#     Sends a prompt to the LocalLLM and retrieves the generated response.
#
#     Args:
#         prompt (str): The user's input prompt to be sent to the language model.
#         model (str): The model to use for generating the response.
#
#     Returns:
#         - generated_content (str): The content generated by the model.
#         - input_tokens (int): The number of tokens in the input prompt.
#         - output_tokens (int): The number of tokens in the generated output.
#
#     """
#     model_path = MODEL_PATHS.get(model)
#     if not model_path:
#         raise ValueError(f"Model '{model}' not found in the dictionary.")
#
#     load_in_4bit_config = BitsAndBytesConfig(
#         load_in_4bit=True,
#         bnb_4bit_compute_dtype=torch.float16,
#         bnb_4bit_use_double_quant=True,
#     )
#
#     tokenizer = AutoTokenizer.from_pretrained(model_path)
#
#     if tokenizer.pad_token_id is None:
#         tokenizer.pad_token_id = tokenizer.eos_token_id
#
#     model = AutoModelForCausalLM.from_pretrained(
#         model_path,
#         quantization_config=load_in_4bit_config,
#         device_map="auto",
#     )
#
#     inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
#
#     with torch.no_grad():
#         output = model.generate(
#             inputs['input_ids'],
#             attention_mask=inputs['attention_mask'],
#             pad_token_id=tokenizer.pad_token_id,
#             max_new_tokens=512,
#             temperature=1.0,
#             top_p=0.9,
#             do_sample=True
#         )
#
#     response = tokenizer.decode(output[0], skip_special_tokens=True)
#
#     generated_content = response[len(prompt):].lstrip()
#
#     input_tokens = inputs['input_ids'].shape[1]
#     output_tokens = output.shape[1] - input_tokens
#
#     return generated_content, input_tokens, output_tokens


if __name__ == "__main__":
    prompt = "Hello!"

    result = get_deepseek_response(prompt)

    if result:
        model_used, response_text, input_tokens, output_tokens = result
        print("=== DeepSeek API Test ===")
        print(f"Model: {model_used}")
        print(f"Response: {response_text}")
        print(f"Input Tokens: {input_tokens}")
        print(f"Output Tokens: {output_tokens}")
    else:
        print("Failed to get a response from the DeepSeek API.")

    result = get_chatgpt_response(prompt)

    if result:
        model_used, response_text, input_tokens, output_tokens = result
        print("=== ChatGPT API Test ===")
        print(f"Model: {model_used}")
        print(f"Response: {response_text}")
        print(f"Input Tokens: {input_tokens}")
        print(f"Output Tokens: {output_tokens}")
    else:
        print("Failed to get a response from ChatGPT API.")

    # local_llm = "Llama-2-7b"
    # result = get_local_response(prompt, local_llm)
    #
    # if result:
    #     response_text, input_tokens, output_tokens = result
    #     print("=== LocalLLM Test ===")
    #     print(f"Model: {local_llm}")
    #     print(f"Response: {response_text}")
    #     print(f"Input Tokens: {input_tokens}")
    #     print(f"Output Tokens: {output_tokens}")
    # else:
    #     print("Failed to get a response from LocalLLM.")

